# Site settings
title: Vets Code 2
header-img: img/home-bg.png
email: jerred.stahlberg@yahoo.com
copyright_name: Jstahl23
description: > # this means to ignore newlines until "baseurl:"
  Follow my transition from Soldier to Developer...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jstahl23
learn_profile: Jstahl23
email_username: jerred.stahlberg@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
